In [1]:
%matplotlib inline

# 01-03_6

In [2]:
import numpy as np

def test_run():
    x = np.array([(2,3,4)]) #1d array
    y = np.array([(2,3,4),(5,6,7)]) #2d array
    print(x)
    print(y)

if __name__ == "__main__":
    test_run()

[[2 3 4]]
[[2 3 4]
 [5 6 7]]


# 01-03_7

In [12]:
import numpy as np

def test_run():
    print(np.ones((5,4), dtype=np.int_))
    
if __name__ == "__main__":
    test_run()

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


# 01-03_9

In [19]:
import numpy as np

def test_run():
    print(np.random.random((5,4)))
    print(np.random.normal(size=(2,3)))
    
if __name__ == "__main__":
    test_run()

[[0.14593814 0.88242945 0.5362681  0.66918726]
 [0.98996544 0.32373113 0.21383734 0.17410177]
 [0.07363237 0.39531794 0.97931721 0.11632515]
 [0.86269979 0.20900506 0.57269185 0.68658462]
 [0.83322463 0.30243491 0.64281425 0.97971903]]
[[-0.4033092   0.33105755 -1.02760726]
 [-0.63658768  0.45196607 -0.52882886]]


# 01-03_10

In [8]:
import numpy as np

def test_run():
    a = np.random.random((5,4))
    print(a)
    print(a.shape)
    print(a.shape[0])
    print(a.shape[1])
    print(len(a.shape))
    print(a.size)
    print(a.dtype)
    
if __name__ == "__main__":
    test_run()

[[0.65399324 0.98089014 0.6670436  0.68049342]
 [0.09856272 0.56663741 0.98891352 0.45306685]
 [0.87979165 0.75785047 0.24817023 0.65107673]
 [0.39943185 0.90656164 0.20312837 0.21884764]
 [0.52996945 0.06769745 0.33542689 0.3395737 ]]
(5, 4)
5
4
2
20
float64


# 01-03_11

In [18]:
import numpy as np

def test_run():
    np.random.seed(693)
    a = np.random.randint(0,10, size=(5,4))
    print("Array:\n", a)
    print("Sum of all elements: ", a.sum())
    print("Sum of each column: ", a.sum(axis=0))
    print("Sum of each row: ", a.sum(axis=1))
    print("Minimum of each column: ", a.min(axis=0))        
    print("Maximum of each row: ", a.max(axis=1))  
    print("Mean of all elements: ", a.mean())  
    
    
    
if __name__ == "__main__":
    test_run()

Array:
 [[2 0 5 1]
 [1 3 4 4]
 [9 2 9 1]
 [9 3 7 5]
 [4 7 0 3]]
Sum of all elements:  79
Sum of each column:  [25 15 25 14]
Sum of each row:  [ 8 12 21 24 14]
Minimum of each column:  [1 0 0 1]
Maximum of each row:  [5 4 9 9 7]
Mean of all elements:  3.95


# 01-03_13

In [20]:
import time
import numpy as np

def test_run():
    t1 = time.time()
    print("ML4T")
    t2 = time.time()
    print("The time taken by the print statement is", t2 - t1, " seconds")
    
    
    
if __name__ == "__main__":
    test_run()

ML4T
The time taken by the print statement is 7.033348083496094e-05  seconds


# 01-03_15

In [26]:
import numpy as np

def test_run():
    a = np.random.rand(5,4)
    print("Array:\n", a)
    
    element = a[3,2]
    print(element)
    
    print(a[0,1:3])
    print(a[0:2,0:2])
    print(a[:,0:3:2])
    
    
if __name__ == "__main__":
    test_run()

Array:
 [[0.89069703 0.02150696 0.64708838 0.7698965 ]
 [0.30164914 0.89814836 0.66131866 0.48146885]
 [0.5483519  0.36432737 0.92344833 0.90806181]
 [0.42703277 0.82115064 0.89385338 0.04992084]
 [0.51226014 0.45752905 0.98503736 0.43623981]]
0.8938533812431938
[0.02150696 0.64708838]
[[0.89069703 0.02150696]
 [0.30164914 0.89814836]]
[[0.89069703 0.64708838]
 [0.30164914 0.66131866]
 [0.5483519  0.92344833]
 [0.42703277 0.89385338]
 [0.51226014 0.98503736]]


# 01-03_16

In [34]:
import numpy as np

def test_run():
    a = np.random.rand(5,4)
    print("Array:\n", a)
    
    """a[0,0] = 1
    print("\nmodified (replaced one element):\n", a)
    
    a[0,:] = 2
    print("\nmodified (replaced a row with a single value):\n", a)    
    
    a[:,1] = 2
    print("\nmodified (replaced a column with a single value):\n", a) """
    
    a[:, 3] = [1,2,3,4,5]
    print("\nmodified (replaced a column with list):\n", a)  


if __name__ == "__main__":
    test_run()

Array:
 [[0.11814791 0.84030607 0.07553637 0.58614074]
 [0.59835773 0.83043358 0.75076269 0.95055117]
 [0.63643792 0.81801152 0.47261619 0.53699651]
 [0.5408923  0.69649196 0.89112555 0.34330453]
 [0.87336551 0.0273596  0.60719079 0.85376483]]

modified (replaced a column with list):
 [[0.11814791 0.84030607 0.07553637 1.        ]
 [0.59835773 0.83043358 0.75076269 2.        ]
 [0.63643792 0.81801152 0.47261619 3.        ]
 [0.5408923  0.69649196 0.89112555 4.        ]
 [0.87336551 0.0273596  0.60719079 5.        ]]


# 01-03_17

In [36]:
import numpy as np

def test_run():
    a = np.random.rand(5)
    print(a)
    indices = np.array([1,1,2,3])
    print(a[indices])

    


if __name__ == "__main__":
    test_run()

[0.82204461 0.92555613 0.23630744 0.43719997 0.81071398]
[0.92555613 0.92555613 0.23630744 0.43719997]


# 01-03_18

In [41]:
import numpy as np

def test_run():
    a = np.array([(20,25,10,23,26,32,10,5,0),(0,2,50,20,0,1,28,5,0)])
    print(a)

    mean = a.mean()
    print(mean)

    print(a[a<mean])
    
    a[a<mean] = mean
    print(a)

if __name__ == "__main__":
    test_run()

[[20 25 10 23 26 32 10  5  0]
 [ 0  2 50 20  0  1 28  5  0]]
14.277777777777779
[10 10  5  0  0  2  0  1  5  0]
[[20 25 14 23 26 32 14 14 14]
 [14 14 50 20 14 14 28 14 14]]


# 01-03_19

In [56]:
import numpy as np

def test_run():
    a = np.array([(1,2,3,4,5), (10,20,30,40,50)])
    b = np.array([(100,200,300,400,500), (1,2,3,4,5)])
    print("Original array a:\n", a)
    print("\nOriginal array b:\n", b)   
    print("\nMultiply a by 2:\n", 2 * a)
    print("\nDivide a by 2:\n", a / 2)
    print("\nDivide a by 2:\n", a / 2.0)
    print("\nAdd a + b\n", a+b)
    print("\nAdd a - b\n", a-b)
    print("\nAdd a * b\n", a*b)
    print("\nAdd a / b\n", a/b)


if __name__ == "__main__":
    test_run()

Original array a:
 [[ 1  2  3  4  5]
 [10 20 30 40 50]]

Original array b:
 [[100 200 300 400 500]
 [  1   2   3   4   5]]

Multiply a by 2:
 [[  2   4   6   8  10]
 [ 20  40  60  80 100]]

Divide a by 2:
 [[ 0.5  1.   1.5  2.   2.5]
 [ 5.  10.  15.  20.  25. ]]

Divide a by 2:
 [[ 0.5  1.   1.5  2.   2.5]
 [ 5.  10.  15.  20.  25. ]]

Add a + b
 [[101 202 303 404 505]
 [ 11  22  33  44  55]]

Add a - b
 [[ -99 -198 -297 -396 -495]
 [   9   18   27   36   45]]

Add a * b
 [[ 100  400  900 1600 2500]
 [  10   40   90  160  250]]

Add a / b
 [[ 0.01  0.01  0.01  0.01  0.01]
 [10.   10.   10.   10.   10.  ]]
